import { resolveConfig } from '../../config/defaults'
import { expandRoles, matchesPattern } from '../../access/engine'
import { buildNav } from '../../navigation/buildNav'
import { copyFor } from '../../modules/types'
import type { AdminConfig, ResolvedAdminConfig } from '../../config/types'
import type { NavItem, NavSection } from '../../navigation/types'
import type { EndpointDescriptor, ResourceDescriptor } from '../../data/types'
import { findUnserializable } from '../../config/serialize'

export interface GeneratedFile {
  name: string
  content: string
}

export interface DocsContext {
  config: ResolvedAdminConfig
  packageName: string
  configPath: string
}

/**
 * Documentation generated from the consumer's own config.
 *
 * The point of generating rather than shipping a template: the output names
 * *their* endpoints, *their* cookie, *their* roles and *their* routes. A generic
 * README tells a new developer how the library works; this tells them how their
 * installation works, and it cannot go stale while it is regenerated in CI
 * (`admin-kit docs --check`).
 */
export function generateDocs(config: AdminConfig, options: { packageName?: string; configPath?: string } = {}): GeneratedFile[] {
  const ctx: DocsContext = {
    config: resolveConfig(config),
    packageName: options.packageName ?? '@cortejojicoy/admin-kit',
    configPath: options.configPath ?? 'admin.config.ts',
  }

  return [
    { name: 'README.md', content: indexDoc(ctx) },
    { name: 'getting-started.md', content: gettingStarted(ctx) },
    { name: 'auth.md', content: authDoc(ctx) },
    { name: 'access.md', content: accessDoc(ctx) },
    { name: 'navigation.md', content: navigationDoc(ctx) },
    { name: 'resources.md', content: resourcesDoc(ctx) },
    { name: 'configuration.md', content: configurationDoc(ctx) },
  ]
}

const GENERATED = '<!-- Generated by `admin-kit docs`. Edits will be overwritten. -->'

function header(title: string, intro: string): string {
  return `${GENERATED}\n\n# ${title}\n\n${intro}\n`
}

/* --------------------------------- index --------------------------------- */

function indexDoc(ctx: DocsContext): string {
  const { config } = ctx
  const panels: string[] = []
  if (config.panels.app.enabled) panels.push(`app panel (launcher) at \`${config.panels.app.home}\``)
  if (config.panels.admin.enabled) panels.push(`admin panel (sidebar) at \`${config.panels.admin.basePath}\``)

  return (
    header(`${config.app.name} — admin documentation`,
      `Generated from [\`${ctx.configPath}\`](../${ctx.configPath}) by \`admin-kit docs\`.`) +
    `
## What this install is

| | |
| --- | --- |
| App | ${config.app.name} |
| Router | \`${config.router}\` |
| Panels | ${panels.join('; ') || 'none' } |
| Auth provider | \`${config.auth.provider}\` |
| Modules | ${config.modules.length} |
| Resources | ${config.resources.length} |
| Roles defined | ${Object.keys(config.access.roles ?? {}).length} |

## Pages

- [Getting started](./getting-started.md) — mount the provider, the panels and the login page
- [Authentication](./auth.md) — endpoints, session storage, environment variables
- [Access control](./access.md) — the three gates, the role matrix, the guards
- [Navigation](./navigation.md) — the nav tree and who can see each entry
- [Resources](./resources.md) — every CRUD endpoint and the screens for it
- [Configuration](./configuration.md) — every value set, every default inherited
`
  )
}

/* ----------------------------- getting started ---------------------------- */

function gettingStarted(ctx: DocsContext): string {
  const { config, packageName } = ctx
  const app = config.panels.app
  const admin = config.panels.admin
  const isApp = config.router === 'app'

  return (
    header('Getting started', `How to mount ${config.app.name} in this codebase.`) +
    `
## 1. Install and import the stylesheet

\`\`\`bash
pnpm add ${packageName}
\`\`\`

\`\`\`ts
// ${isApp ? 'app/layout.tsx' : 'pages/_app.tsx'}
import '${packageName}/styles.css'
\`\`\`

## 2. Mount the provider

${isApp ? appRouterSnippet(ctx) : pagesRouterSnippet(ctx)}

## 3. The panels

${app.enabled ? `\`${app.home}\` renders the launcher:

\`\`\`tsx
import { AppShell, AppLauncher } from '${packageName}/ui'

export default function Page() {
  return (
    <AppShell>
      <AppLauncher />
    </AppShell>
  )
}
\`\`\`
` : '_The app panel is disabled in this config._\n'}
${admin.enabled ? `\`${admin.basePath}\` renders the sidebar panel, guarded at the layout:

\`\`\`tsx
// app${admin.basePath}/layout.tsx
import { AdminShell } from '${packageName}/ui'
import { getServerSession, rolesFromSession, requireAdmin } from '${packageName}/server'
import { adminConfig } from '@/${ctx.configPath.replace(/\.[^.]+$/, '')}'
import { serverConfig } from '@/admin.server'

export default async function AdminLayout({ children }) {
  const session = await getServerSession(adminConfig, await requestFromHeaders(), { serverConfig })
  await requireAdmin(adminConfig, { roles: rolesFromSession(adminConfig, session) })
  return <AdminShell>{children}</AdminShell>
}
\`\`\`
` : '_The admin panel is disabled in this config._\n'}
## 4. The login page

\`${config.auth.loginPage.path}\` renders the sign-in form:

\`\`\`tsx
import { LoginPage } from '${packageName}/ui'

export default function Page() {
  return <LoginPage />
}
\`\`\`

## 5. Protect the routes

\`\`\`ts
// middleware.ts
import { createAdminMiddleware } from '${packageName}/middleware'
import { adminConfig } from './${ctx.configPath.replace(/\.[^.]+$/, '')}'

export default createAdminMiddleware(adminConfig, { secret: process.env.JWT_SECRET })
export const config = { matcher: ['/((?!_next|api/auth|favicon).*)'] }
\`\`\`

> Middleware redirects; it does not authorize. See [Access control](./access.md#guards).
`
  )
}

function appRouterSnippet(ctx: DocsContext): string {
  const { packageName, configPath } = ctx
  const importPath = configPath.replace(/\.[^.]+$/, '')
  return `\`\`\`tsx
// app/layout.tsx  (server component)
import { AdminProvider } from '${packageName}/client'
import { serializeConfig } from '${packageName}'
import { adminConfig } from '@/${importPath}'
import '${packageName}/styles.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        {/* serializeConfig strips functions so the config can cross into a client component */}
        <AdminProvider config={serializeConfig(adminConfig)} icons={icons}>
          {children}
        </AdminProvider>
      </body>
    </html>
  )
}
\`\`\``
}

function pagesRouterSnippet(ctx: DocsContext): string {
  const { packageName, configPath } = ctx
  return `\`\`\`tsx
// pages/_app.tsx
import { AdminProvider } from '${packageName}/client'
import { adminConfig } from '@/${configPath.replace(/\.[^.]+$/, '')}'
import '${packageName}/styles.css'

export default function App({ Component, pageProps }) {
  return (
    <AdminProvider config={adminConfig}>
      <Component {...pageProps} />
    </AdminProvider>
  )
}
\`\`\``
}

/* ----------------------------------- auth --------------------------------- */

function authDoc(ctx: DocsContext): string {
  const { config, packageName } = ctx
  const jwt = config.auth.jwt
  const storage = jwt?.tokenStorage ?? 'server-cookie'
  const cookie = jwt?.cookieName ?? 'admin_kit_token'

  const rows: string[] = []
  if (jwt?.endpoints) {
    for (const [name, path] of Object.entries(jwt.endpoints)) {
      if (path) rows.push(`| \`${name}\` | \`${path}\` |`)
    }
  }

  return (
    header('Authentication', `Provider: \`${config.auth.provider}\`.`) +
    `
## Endpoints

${rows.length ? `| Operation | Path |\n| --- | --- |\n${rows.join('\n')}` : '_No JWT endpoints configured._'}

## Session storage

\`${storage}\`${storageNote(storage, cookie)}

## Routes

| | |
| --- | --- |
| Login page | \`${config.auth.loginPage.path}\` |
| After login | \`${config.auth.afterLoginRedirect}\` |
| After logout | \`${config.auth.afterLogoutRedirect}\` |
| Public routes | ${(config.auth.publicRoutes ?? []).map((r) => `\`${r}\``).join(', ') || '—'} |

## Environment

| Variable | Used by | Notes |
| --- | --- | --- |
| \`JWT_SECRET\` | middleware, \`getServerSession\` | Server-only. Keep it in \`admin.server.ts\`, never in \`${ctx.configPath}\`. |

${storage === 'server-cookie' ? `## The login route

With \`server-cookie\` storage the browser never sees the token — your login
route sets it:

\`\`\`ts
// app/api/auth/login/route.ts
import { sessionCookie } from '${packageName}/server'

export async function POST(request: Request) {
  const token = await signInAgainstYourBackend(await request.json())
  return new Response(JSON.stringify({ ok: true }), {
    headers: {
      'Content-Type': 'application/json',
      'Set-Cookie': sessionCookie(token, { name: '${cookie}', maxAge: 60 * 60 * 8 }),
    },
  })
}
\`\`\`
` : ''}`
  )
}

function storageNote(storage: string, cookie: string): string {
  switch (storage) {
    case 'server-cookie':
      return ` — the token lives in an \`HttpOnly; Secure\` cookie named \`${cookie}\`, set by your login route. Script cannot read it, so an XSS cannot exfiltrate the session.`
    case 'js-cookie':
      return ` — the client writes a cookie named \`${cookie}\`. **Readable by any script on the origin**, so an XSS can steal the session. Prefer \`server-cookie\` unless something genuinely needs the token in JS.`
    case 'localStorage':
      return ` — stored under \`${cookie}\` in \`localStorage\`. Readable by script, and invisible to middleware and server components, so route protection has to be client-side.`
    default:
      return ' — held in memory only, so the session is lost on reload.'
  }
}

/* ---------------------------------- access -------------------------------- */

function accessDoc(ctx: DocsContext): string {
  const { config, packageName } = ctx
  const access = config.access
  const roles = Object.keys(access.roles ?? {})

  const axes = [
    ['Catalog', access.catalog?.endpoint ? `\`${access.catalog.endpoint}\`` : '_not configured_',
      access.catalog?.endpoint ? 'falls back to the declared modules' : 'the declared modules are the list'],
    ['Entitlement', access.entitlements?.endpoint ? `\`${access.entitlements.endpoint}\`` : '_not configured_',
      access.entitlements?.endpoint ? `\`${access.entitlements.onUnavailable ?? 'allow'}\` on failure` : 'every module is entitled'],
    ['Permission', access.permissions?.endpoint ? `\`${access.permissions.endpoint}\`` : 'the session payload',
      `\`${access.permissions?.onUnavailable ?? 'allow'}\` on failure`],
  ]

  return (
    header('Access control', 'Three independent gates decide whether a module is reachable.') +
    `
## The gates

| Axis | Question | Source | If the source cannot be read |
| --- | --- | --- | --- |
| **Catalog** | Does the module exist and is it active? | ${axes[0][1]} | ${axes[0][2]} |
| **Entitlement** | May this tenant run it? | ${axes[1][1]} | ${axes[1][2]} |
| **Permission** | May this user open it? | ${axes[2][1]} | ${axes[2][2]} |

Failing *open* is deliberate where it applies: a control-plane read that failed
must not lock a paying customer out of software they have paid for. Set
\`onUnavailable: 'deny'\` on an axis where absence genuinely means no.

Access levels are \`none\` < \`view\` < \`full\`. The default required level is
\`${access.defaultRequiredLevel ?? 'view'}\`.

## Roles

${roles.length ? roleMatrix(ctx) : '_No roles declared. Permissions come straight from the permissions source._'}

Administrators: ${(access.adminRoles ?? ['admin']).map((r) => `\`${r}\``).join(', ')}.

## Guards

Hiding a control is not authorization — a hidden button is still a reachable
endpoint. Every route that matters gets a server-side gate:

\`\`\`ts
import { requireModule, assertPermission, getServerSession, rolesFromSession } from '${packageName}/server'

const session = await getServerSession(adminConfig, request, { serverConfig })
const roles = rolesFromSession(adminConfig, session)

await requireModule(adminConfig, 'BILLING', { request, roles })      // may they open the page?
await assertPermission(adminConfig, 'billing:post', { request, roles }) // may they perform the write?
\`\`\`

In the UI, \`<Can>\` and \`<RequirePermission>\` decide what renders:

\`\`\`tsx
import { Can } from '${packageName}/access'

<Can do="users:create">
  <Button>New user</Button>
</Can>
\`\`\`
`
  )
}

function roleMatrix(ctx: DocsContext): string {
  const { config } = ctx
  const access = config.access
  const roles = Object.keys(access.roles ?? {})

  // Every code mentioned anywhere, so the matrix covers what the app actually
  // guards rather than only what the roles happen to list.
  const codes = new Set<string>()
  for (const mod of config.modules) {
    codes.add(mod.code)
    for (const extra of mod.accessCodes ?? []) codes.add(extra)
  }
  for (const resource of config.resources) {
    for (const code of Object.values(resource.permissions ?? {})) if (code) codes.add(code)
  }
  if (codes.size === 0) {
    for (const patterns of Object.values(access.roles ?? {})) {
      for (const p of patterns) codes.add(p)
    }
  }

  const sorted = [...codes].sort()
  const head = `| Permission | ${roles.join(' | ')} |`
  const rule = `| --- | ${roles.map(() => '---').join(' | ')} |`
  const rows = sorted.map((code) => {
    const cells = roles.map((role) => {
      const { grants } = expandRoles([role], access)
      const denied = (access.deny?.[role] ?? []).some((p) => matchesPattern(p, code))
      if (denied) return '✗ denied'
      return grants.some((p) => matchesPattern(p, code)) ? '✓' : '—'
    })
    return `| \`${code}\` | ${cells.join(' | ')} |`
  })

  const hierarchy = Object.entries(access.hierarchy ?? {})
  const inheritance = hierarchy.length
    ? `\n\nRole inheritance: ${hierarchy.map(([r, parents]) => `\`${r}\` → ${parents.map((p) => `\`${p}\``).join(', ')}`).join('; ')}. Expanded transitively above.`
    : ''

  return `${head}\n${rule}\n${rows.join('\n')}${inheritance}`
}

/* -------------------------------- navigation ------------------------------ */

function navigationDoc(ctx: DocsContext): string {
  const { config } = ctx

  // Built exactly the way <AdminShell> builds it: the admin panel's own
  // sections if it declares any, otherwise the top-level navigation — and
  // **not** the module descriptors, which drive the launcher rather than the
  // sidebar. Generated documentation is only worth having if it describes what
  // the app actually renders.
  const sections = buildNav({
    sections: config.panels.admin.sections ?? config.navigation.sections,
  })

  const tiles = config.modules.filter((m) => (m.placement ?? 'tile') === 'tile')
  const dock = config.modules.filter((m) => m.placement === 'dock')

  return (
    header('Navigation', 'What appears where, and who can see it.') +
    `
## Launcher (app panel)

${tiles.length ? `### Tiles

| Module | Route | Requires | Emphasis |
| --- | --- | --- | --- |
${tiles.map((m) => `| ${m.title} | \`${m.href}\` | ${codeList([m.code, ...(m.accessCodes ?? [])])} | ${m.emphasis ?? '—'} |`).join('\n')}
` : '_No tile modules._\n'}
${dock.length ? `### Quick-access dock

Order is fixed by \`panels.app.dockOrder\` rather than by catalog order, so the
cell under the user's thumb does not move when the backend reorders its list.

| Module | Route | Requires |
| --- | --- | --- |
${orderDock(dock, config.panels.app.dockOrder).map((m) => `| ${m.title} | \`${m.href}\` | ${codeList([m.code, ...(m.accessCodes ?? [])])} |`).join('\n')}
` : ''}
## Sidebar (admin panel)

${
  config.panels.admin.enabled === false
    ? '_The admin panel is disabled._'
    : sections.length
      ? `Built from \`${config.panels.admin.sections ? 'panels.admin.sections' : 'navigation.sections'}\`, filtered by the access engine at render time.\n\n` +
        sections.map((s) => renderSection(s)).join('\n')
      : '_No sections declared, so the sidebar is empty._'
}

## Module descriptions

${config.modules.length ? config.modules.map((m) => `- **${m.title}** (\`${m.code}\`) — ${copyFor(m.description, config.app.flavor) ?? '_no description_'}`).join('\n') : '_None._'}
`
  )
}

type DockRow = { code: string; title: string; href: string; accessCodes?: string[] }

function orderDock(modules: DockRow[], order: string[] = []): DockRow[] {
  if (order.length === 0) return modules
  const byCode = new Map(modules.map((m) => [m.code, m]))
  const listed = order.map((c) => byCode.get(c)).filter((m): m is DockRow => m != null)
  const rest = modules.filter((m) => !order.includes(m.code))
  return [...listed, ...rest]
}

function renderSection(section: NavSection): string {
  const title = section.label ?? '(unlabelled)'
  const lines = section.items.map((item) => renderItem(item, 0))
  return `### ${title}\n\n${lines.join('\n')}\n`
}

function renderItem(item: NavItem, depth: number): string {
  const indent = '  '.repeat(depth)
  const requires = codeList([...(item.permissions ?? []), ...(item.accessCodes ?? [])])
  const target = item.href ? ` → \`${item.href}\`` : ''
  const gate = requires === '—' ? '' : ` _(requires ${requires})_`
  const self = `${indent}- ${item.label}${target}${gate}`
  const children = (item.children ?? []).map((child) => renderItem(child, depth + 1))
  return [self, ...children].join('\n')
}

function codeList(codes: string[]): string {
  const unique = [...new Set(codes.filter(Boolean))]
  return unique.length ? unique.map((c) => `\`${c}\``).join(', ') : '—'
}

/* -------------------------------- resources ------------------------------- */

function resourcesDoc(ctx: DocsContext): string {
  const { config, packageName } = ctx
  if (config.resources.length === 0) {
    return (
      header('Resources', 'No resources declared yet.') +
      `
Add one to \`${ctx.configPath}\`:

\`\`\`ts
resources: [
  {
    name: 'users',
    endpoints: {
      list:   '/api/users',
      one:    '/api/users/:id',
      create: { method: 'POST',   path: '/api/users' },
      update: { method: 'PATCH',  path: '/api/users/:id' },
      remove: { method: 'DELETE', path: '/api/users/:id' },
    },
    fields: [
      { name: 'id', label: 'ID', readOnly: true },
      { name: 'email', type: 'email', required: true, sortable: true },
    ],
    permissions: { list: 'users:list', create: 'users:create' },
  },
]
\`\`\`
`
    )
  }

  return (
    header('Resources', `${config.resources.length} declared. Each is a set of endpoints plus the fields that drive the generated screens.`) +
    config.resources.map((resource) => resourceSection(resource, packageName)).join('\n---\n\n')
  )
}

function resourceSection(resource: ResourceDescriptor, packageName: string): string {
  const endpoints = Object.entries(resource.endpoints).filter(([, value]) => value != null)
  const idField = resource.idField ?? 'id'

  const endpointRows = endpoints.map(([op, value]) => {
    const descriptor: EndpointDescriptor = typeof value === 'string' ? { path: value } : (value as EndpointDescriptor)
    const method = descriptor.method ?? defaultMethod(op)
    const permission = resource.permissions?.[op]
    return `| \`${op}\` | \`${method}\` | \`${descriptor.path}\` | ${permission ? `\`${permission}\`` : '—'} |`
  })

  const fieldRows = (resource.fields ?? []).map(
    (field) =>
      `| \`${field.name}\` | ${field.type ?? 'string'} | ${field.required ? 'yes' : '—'} | ${field.inList === false ? '—' : '✓'} | ${field.inForm === false || field.readOnly ? '—' : '✓'} |`,
  )

  return `
## ${resource.labelPlural ?? resource.label ?? resource.name}

Resource name: \`${resource.name}\` · id field: \`${idField}\` · page size: ${resource.perPage ?? 25}

### Endpoints

| Operation | Method | Path | Permission |
| --- | --- | --- | --- |
${endpointRows.join('\n')}

### Fields

${fieldRows.length ? `| Field | Type | Required | In list | In form |\n| --- | --- | --- | --- | --- |\n${fieldRows.join('\n')}` : '_No fields declared — the generated table and form will be empty._'}

### Screens

\`\`\`tsx
import { ResourceTable, ResourceForm, ResourceShow } from '${packageName}/ui'

<ResourceTable resource="${resource.name}" hrefFor="/${resource.name}/:${idField}" />
<ResourceForm resource="${resource.name}" />
<ResourceShow resource="${resource.name}" id={id} />
\`\`\`

### Hooks

\`\`\`ts
import { useList, useOne, useCreate, useUpdate, useDelete } from '${packageName}/data'

const { rows, total, loading, page, setPage } = useList('${resource.name}')
const { data } = useOne('${resource.name}', id)
const create = useCreate('${resource.name}')
\`\`\`
`
}

function defaultMethod(op: string): string {
  switch (op) {
    case 'create':
      return 'POST'
    case 'update':
      return 'PATCH'
    case 'remove':
      return 'DELETE'
    default:
      return 'GET'
  }
}

/* ------------------------------ configuration ----------------------------- */

function configurationDoc(ctx: DocsContext): string {
  const { config } = ctx
  const unserializable = findUnserializable({
    app: config.app,
    navigation: config.navigation,
    modules: config.modules,
    access: config.access,
    panels: config.panels,
  })

  return (
    header('Configuration', 'Every value this install sets, and every default it inherits.') +
    `
## Resolved configuration

\`\`\`json
${JSON.stringify(redact(config), null, 2)}
\`\`\`

## Serializability

The config is passed from server components into a client provider, so the parts
listed above must be plain data. Functions belong in \`resources[].map\`,
\`auth.custom\` and plugins — all of which \`serializeConfig()\` strips at the
boundary.

${unserializable.length
  ? `> **${unserializable.length} unserializable value(s) found** in the parts that must cross the boundary:\n>\n${unserializable.map((p) => `> - \`${p}\``).join('\n')}\n>\n> Replace functions with declarative fields, and \`ReactNode\` icons with \`iconKey\` strings.`
  : 'No unserializable values found in those parts. ✓'}
`
  )
}

/** Never print anything secret into a file people commit. */
function redact(config: ResolvedAdminConfig): unknown {
  const clone = JSON.parse(
    JSON.stringify(config, (key, value) =>
      /secret|token|password|clientSecret/i.test(key) ? '«redacted»' : value,
    ),
  ) as Record<string, unknown>
  delete clone.plugins
  return clone
}
